import { Navbar } from "@/components/ui/site-navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`flex flex-col h-screen dark ${inter.className}`}>
        <Navbar />
        <main className="container my-16 grow">{children}</main>
      </body>
    </html>
  );
}
