version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "9000:5432"
    container_name: server-actions-prisma
