version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    volumes:
      - "./mongo-data:/data/db"
    ports:
      - "27017:27017"
    container_name: mongodb_c2